### ISSUE TITLE
JOSS Submission/Review process

### ISSUE THREAD

**Issue by iimog** [chloroExtractorTeam/chloroExtractor#2]
From http://joss.theoj.org/about#author_guidelines

>What are your requirements for submission?
>
>  - Your software should be open source as per the OSI definition
>  - Your software should have a research application
>  - You should be a major contributor to the software you are submitting
>   - Should be a significant contribution to the available open source software that either enables some new research challenges to be addressed or makes addressing research challenges significantly better (e.g., faster, easier, simpler)
>   - Should be feature complete (no half-baked solutions)

**Comment by greatfireball** [comment]
Submission to [The Journal of Open Source Software](joss.theoj.org) incl. a zenodo DOI: [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.998262.svg)](https://doi.org/10.5281/zenodo.998262) was done today and is available here []()

**Comment by greatfireball** [comment]
Will close that issue, due to we got published :)
