### ISSUE TITLE
Comma missing in default ptx.cfg

### ISSUE THREAD

**Issue by iimog** [chloroExtractorTeam/chloroExtractor#23]
There is a comma missing in line 130 of the current default ptx.cfg leading to an error. Adding the comma fixes the problem.
https://github.com/greatfireball/chloroExtractor/blob/2e2a6cbe5d4046a16b2969c29b4074807cf7c0c7/ptx.cfg#L130

**Comment by greatfireball** [comment]
Should be fixes with hotfix/comma-issue, please review @iimog
