### ISSUE TITLE
Name is ambiguous

### ISSUE THREAD

**Issue by greatfireball** [chloroExtractorTeam/chloroExtractor#30]
The name `ptx` is also used for a tool installed by default in the Ubuntu environment. Therefore, we should think about renaming the tool. Otherwise, we should include that ambiguity in the `Readme.md` to avoid confusion.

**Comment by thackl** [comment]
I have no particular attachment to that name, just chose it 'cause it's short. My reasoning for moving away from `chloroExtractor` as a name was purely motivated by the idea that it should also be possible to assemble other stuff, like mitochondria, hence _plastidExtractor_ (lazy: ptx)

Is `ptx` the current master script file? What about `chloroExtractor`, is that still in use? I don't think that we'll be looking into mitochondria, so I'd be more than fine with moving back to `chloroExtractor` as the name for the master script (which ever that is)

**Comment by iimog** [comment]
I'm also happy with any name. So here I collect some suggestions from previous discussions. We just have to pick one:
 - ptX
 - plastidExtractor
 - plastidXtractor
 - plastidX
 - chloroExtractor
 - chloroXtractor
 - chloroX
 - cpx

I'll start a quick poll in slack

**Comment by greatfireball** [comment]
Decision was made:
we will keep chloroExtractor
