### ISSUE TITLE
Is -o option of ptx used at all?

### ISSUE THREAD

**Issue by iimog** [chloroExtractorTeam/chloroExtractor#55]
The synopsis of ptx is as follows:
```
$ ./ptx [<OPTIONS>] -1 <FQ_1> -2 <FQ_2> -o <ID>
```
However, `-o` seems to be unused as the files are not named that way and neither is it used for the id in the final fasta file. Also the `-d` option seems to default to the current directory and not "ptx" as the `--help` text implies. So for the synopsis `-d` would be much more important than `-o`

**Comment by PfaffS** [comment]
I looked into it and I couldn't find anything why -d is still on the current dir, the last commit on ptx was from thomas which should set the standart dir to ptx. We did not change anything on ptx but we also never testet wether the standart dir is ptx 'cause I always named my dirs.
I also found nothing on the -o issue sry, it should be in an hashref and should used, i don't know why it isn't.

**Comment by greatfireball** [comment]
Identified the problem and fixed it
