### ISSUE TITLE
change default number of threads?

### ISSUE THREAD

**Issue by nterhoeven** [chloroExtractorTeam/chloroExtractor#68]
Currently the default number of threads is 8. 

Maybe it would be a good idea to reduce this to 2 or 4, since most (result of a non-representative study made up in my head) Laptop or Desktop computers have less than 8 threads available.

I am thinking of this with the use-case of doing a quick test with the demo data. A user probably does not think about checking the number of threads then. 
When running more serious analyses on larger computers a user would probably check and adjust the number of threads anyway.

Any opinions on that?

**Comment by greatfireball** [comment]
For travis testing I am already reducing the number of threads to 2... So, I agree and would reduce the threads to 2 or maybe only 1
