### ISSUE TITLE
Example in docker does not work

### ISSUE THREAD

**Issue by jdeligt** [chloroExtractorTeam/chloroExtractor#81]
When I run the example usage:

docker pull chloroextractorteam/chloroextractor # ensure the latest version from docker hub
docker run -v /tmp/chloroExtractor-testrun:/data --rm chloroextractorteam/chloroextractor -1 SRR5216995_1M_1.fastq -2 SRR5216995_1M_2.fastq

It returns an exit state 9:

>All dependencies fulfilled!
>';
>[17-11-17 13:13:23] [PipeWrap] Running 'jf0': jellyfish count -t 2 -m 31 -s 500M -C -o jf0.jf >/data/SRR5216995_1M_1.fastq /data/SRR5216995_1M_2.fastq
>[17-11-17 13:13:36] [PipeWrap] jf0 exited:9
>[17-11-17 13:13:36] [PipeWrap]  at /opt/chloroExtractor/bin/../lib/PipeWrap.pm line 153.

**Comment by iimog** [comment]
Thanks for raising this issue. This is a documentation problem. I assume this only works when there is a folder /tmp/chloroExtractor-testrun with the two SRR fastq files on the host machine, @greatfireball can you please verify and fix the documentation?
Otherwise I can have a closer look when I'm back from South Africa in early December.

**Comment by jdeligt** [comment]
I've bound the data folder in the docker to the right local directory:
docker run -v /Users/jdeligt/data/chloroExtractor/:/data

creating the  /tmp/chloroExtractor-testrun on my machine does help but raises a new issue:
>[17-11-24 07:36:46] [PipeWrap] Running 'fcg': /opt/chloroExtractor/bin/find_cyclic_graph.pl --in ass/assembly_graph.fastg --blastdb /opt/chloroExtractor/bin//../data/cds.nr98.fa --out fcg.fa
>[17-11-24 07:36:46] [fcg] Unable to open file 'ass/assembly_graph.fastg'
>[17-11-24 07:36:46] [PipeWrap] fcg exited:256
>[17-11-24 07:36:46] [PipeWrap]  at /opt/chloroExtractor/bin/../lib/PipeWrap.pm line 153.


Drop me a line when the docker and source documentations are in working order so I can continue the review.

**Comment by DanielAmsel** [comment]
Hi *,
I ran into the same problem as @jdeligt . 
So I assume we both use a macOS system?
I managed to overcome the issue by simply increasing the memory, docker wants to allocate.
In my case, I allowed 5GB (but I think anything larger than the default 2GB would fit).
( https://stackoverflow.com/a/39720010 )

My settings were:
MacBook Pro 13
macOS High Sierra 10.13.1
2.7GHz Intel Core I5
8GB RAM (1867Mhz DDR3)

I took the commands from 
https://github.com/chloroExtractorTeam/chloroExtractor#example

```bash
mkdir -p /tmp/chloroExtractor-testrun
cd /tmp/chloroExtractor-testrun
wget 'https://zenodo.org/record/884449/files/SRR5216995_1M.tar.bz2' -O - | tar xjf -
docker pull chloroextractorteam/chloroextractor
docker run -v /tmp/chloroExtractor-testrun:/data --rm chloroextractorteam/chloroextractor -1 SRR5216995_1M_1.fastq -2 SRR5216995_1M_2.fastq
```
Best,
Daniel

**Comment by jdeligt** [comment]
This does indeed seem to solve the issue.
Please update the documentation to reflect this and the requirement for the directory.

The issue with the source code version is not related to this, do you want me to open a separate issue for this?

**Comment by iimog** [comment]
The documentation is now up to date with version numbers for requirements, information about docker memory requirements and a more consistent description of the demo directory.

Regarding the issue with the source code version, I'm not sure if I can reproduce it. If you don't mind @jdeligt it would be nice to open a separate issue for that.

**Comment by jdeligt** [comment]
Will do. Hopefully tomorrow. I will add as much info as possible to
reproduce.

**Comment by greatfireball** [comment]
As the issue was solved for @jdeligt I will close that issue
