### ISSUE TITLE
Update and add citations

### ISSUE THREAD

**Issue by greatfireball** [chloroExtractorTeam/chloroExtractor#86]
As discussed on our slack channel, we should add some more citations:
- [x] Jellyfish
- [x] Spades
- [x] bowtie2
- [x] NCBI-Blast+
- [x] Samtools
- [x] Bedtools
- [x] GNU R
- [x] _Ghostscript_
- [x] _Python_
- [x] _Perl_
- [x] _diverse perl modules_

**Comment by greatfireball** [comment]
@PfaffS added bowtie2, NCBI-Blast+, Samtools, Bedtools, and GNU R in paper.bib

**Comment by greatfireball** [comment]
@PfaffS please add links to the italic items to paper.md as inline links

**Comment by PfaffS** [comment]
added Ghostscript, Phyton, Perl and Perl moduls as inline links in paper.md

**Comment by greatfireball** [comment]
thx! Will you prepare a pull request and request review by @iimog or myself?

**Comment by PfaffS** [comment]
done, requested a pull. Review by @greatfireball and @iimog

**Comment by greatfireball** [comment]
:+1:

**Comment by greatfireball** [comment]
thx
